basePath: /api/v1
definitions:
  main.PingResponse:
    properties:
      message:
        example: pong
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: A dating application API built with Go and Gin
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Cupid API
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: Health check endpoint that returns pong
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.PingResponse'
      summary: Ping endpoint
      tags:
      - health
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
